### ISSUE TITLE
I know I sound like a complete idiot

### ISSUE THREAD

**Issue by booooooooooooooooooo** [DasEtwas/enginesound#17]
But how do you actually run the app?

**Comment by Friz64** [comment]
Install Rust: https://www.rust-lang.org/tools/install

Install dependencies if you are on Linux (e.g. Ubuntu: `sudo apt-get install libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev`)

Build & Run: `cargo run --release`

**Comment by booooooooooooooooooo** [comment]
Can you run it on MacOS?

**Comment by Friz64** [comment]
I'm pretty confident it will, you should try and see what happens

**Comment by alterfo** [comment]
On Mac I get this

error[E0308]: mismatched types
   --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.23.0/src/platform_impl/macos/util/async.rs:170:55
    |
170 |                 ns_window.setFrame_display_(new_rect, 0);
    |                           -----------------           ^ expected `bool`, found integer
    |                           |
    |                           arguments to this method are incorrect
    |
note: method defined here
   --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cocoa-0.23.0/src/appkit.rs:945:15
    |
945 |     unsafe fn setFrame_display_(self, windowFrame: NSRect, display: BOOL);
    |               ^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.23.0/src/platform_impl/macos/view.rs:391:9
    |
386 | extern "C" fn has_marked_text(this: &Object, _sel: Sel) -> BOOL {
    |                                                            ---- expected `bool` because of return type
...
391 |         (marked_text.length() > 0) as i8
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `bool`, found `i8`

error[E0308]: mismatched types
   --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.23.0/src/platform_impl/macos/window.rs:656:22
    |
656 |         is_zoomed != 0
    |         ---------    ^ expected `bool`, found integer
    |         |
    |         expected because this is `bool`

error[E0308]: mismatched types
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.23.0/src/platform_impl/macos/window.rs:1171:48
     |
1171 |         window.setFrame_display_(current_rect, 0)
     |                -----------------               ^ expected `bool`, found integer
     |                |
     |                arguments to this method are incorrect
     |
note: method defined here
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cocoa-0.23.0/src/appkit.rs:945:15
     |
945  |     unsafe fn setFrame_display_(self, windowFrame: NSRect, display: BOOL);
     |               ^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.23.0/src/platform_impl/macos/window.rs:1178:48
     |
1178 |         window.setFrame_display_(current_rect, 0)
     |                -----------------               ^ expected `bool`, found integer
     |                |
     |                arguments to this method are incorrect
     |
note: method defined here
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cocoa-0.23.0/src/appkit.rs:945:15
     |
945  |     unsafe fn setFrame_display_(self, windowFrame: NSRect, display: BOOL);
     |               ^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.23.0/src/platform_impl/macos/window.rs:1195:48
     |
1195 |         window.setFrame_display_(current_rect, 0)
     |                -----------------               ^ expected `bool`, found integer
     |                |
     |                arguments to this method are incorrect
     |
note: method defined here
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cocoa-0.23.0/src/appkit.rs:945:15
     |
945  |     unsafe fn setFrame_display_(self, windowFrame: NSRect, display: BOOL);
     |               ^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.23.0/src/platform_impl/macos/window.rs:1202:48
     |
1202 |         window.setFrame_display_(current_rect, 0)
     |                -----------------               ^ expected `bool`, found integer
     |                |
     |                arguments to this method are incorrect
     |
note: method defined here
    --> /Users/olegsidorkin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cocoa-0.23.0/src/appkit.rs:945:15
     |
945  |     unsafe fn setFrame_display_(self, windowFrame: NSRect, display: BOOL);
     |               ^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `winit` (lib) due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
